name: build

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14

      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew buildPlugin

      - uses: actions/upload-artifact@v2
        with:
          name: duckit-jetbrains-latest.zip
          path: build/distributions/duckit-jetbrains-*.zip
          if-no-files-found: error

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/distributions/duckit-jetbrains-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Set SHA
        id: shasum
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=sha::"$(shasum -a 256 build/distributions/duckit-jetbrains-*.zip | awk '{printf $1}')"
